[package]
name = "apache-mentor"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
serde = "1.0.219"
serde_json = "1.0.140"
tui-markdown = "0.3.3"
tui-textarea = {version = "0.7.0", features = ["serde", "search"]}
